matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 3.1
      solution: server/glovo_webapi/glovo_webapi.sln
      before_script:
        - cd server/glovo_webapi
      script:
        - dotnet restore
        - cd glovo_webapi
        - dotnet publish -c Release
      after_success:
      
        
      
      
        
