services:
  - docker
language: csharp
mono: none
dotnet: 3.1
solution: server/glovo_webapi/glovo_webapi.sln
install:
  - dotnet tool install --global dotnet-ef
  - export PATH="$HOME/.dotnet/tools":$PATH
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$TRAVIS_BUILD_DIR/flutter/bin:$PATH"
  - flutter config --enable-web

stages:
  - tests
  - name: deploy
    if: branch = devops-task-29

jobs:
  include:
    - stage: deploy
      name: "Backend"
      script:
        - cd $TRAVIS_BUILD_DIR/server/glovo_webapi
        - dotnet restore
        - cd glovo_webapi
        - dotnet publish -c Release -o $TRAVIS_BUILD_DIR/backend_deployment/publish
        - cd $TRAVIS_BUILD_DIR/backend_deployment
        - dotnet ef migrations script --idempotent --project $TRAVIS_BUILD_DIR/server/glovo_webapi/glovo_webapi -o migration.sql
        - echo $HEROKU_API_KEY
        - heroku login
        - heroku pg:psql --app ub-es2020-glovo-webapi < migration.sql
        - heroku container:login
        - heroku container:push web -a ub-es2020-glovo-webapi
        - heroku container:release web -a ub-es2020-glovo-webapi
    - name: "Frontend"
      script: bash $TRAVIS_BUILD_DIR/frontend_deployment/deploy.sh
