services:
  - docker
language: csharp
mono: none
dotnet: 3.1
solution: server/glovo_webapi/glovo_webapi.sln
install:
  - dotnet tool install --global dotnet-ef
  - export PATH="$HOME/.dotnet/tools":$PATH
  - git clone https://github.com/flutter/flutter.git -b beta
  - export PATH="$TRAVIS_BUILD_DIR/flutter/bin:$PATH"
  - flutter config --enable-web

stages:
  - build
  - tests
  - name: deploy
    if: branch = devops-task-29

jobs:
  include:
  
    - stage: tests
      name: "Unit Tests"
      script:
        - echo "TODO"
    - name: "Integration Tests"
      script:
        - echo "TODO"
      
    - stage: deploy
      name: "Backend"
      script: bash $TRAVIS_BUILD_DIR/backend_deployment/deploy.sh
    - name: "Frontend"
      script: bash $TRAVIS_BUILD_DIR/frontend_deployment/deploy.sh
