jobs:
  include:
  - name: Backend
    services:
      - docker
    language: csharp
    mono: none
    dotnet: 3.1
    solution: server/glovo_webapi/glovo_webapi.sln
    install:
      - dotnet tool install --global dotnet-ef
      - export PATH="$HOME/.dotnet/tools":$PATH
    before_script:
      - dotnet-ef
      - cd $TRAVIS_BUILD_DIR/server/glovo_webapi
    script:
      - dotnet restore
      - cd glovo_webapi
      - dotnet publish -c Release -o $TRAVIS_BUILD_DIR/backend_deployment/publish
    deploy:
      provider: script
      script: bash $TRAVIS_BUILD_DIR/backend_deployment/deploy.sh
      on:
        branch: devops-task-29

