CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201027003800_InitialMigration') THEN
    CREATE TABLE "Restaurants" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ImgPath" text NULL,
        CONSTRAINT "PK_Restaurants" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201027003800_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201027003800_InitialMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201030213552_InitialMigration2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201030213552_InitialMigration2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101001222_MigrationProducts') THEN
    CREATE TABLE "Products" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ImgPath" text NULL,
        "Description" text NULL,
        "Price" real NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101001222_MigrationProducts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101001222_MigrationProducts', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101164712_UsersMigration') THEN
    CREATE TABLE "Users" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Email" text NULL,
        "PasswordHash" bytea NULL,
        "PasswordSalt" bytea NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101164712_UsersMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101164712_UsersMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101183159_MigrationProductsOfRestaurant') THEN
    ALTER TABLE "Products" ADD "IdRest" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101183159_MigrationProductsOfRestaurant') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101183159_MigrationProductsOfRestaurant', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201103094826_Deploy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201103094826_Deploy', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    ALTER TABLE "Products" RENAME COLUMN "IdRest" TO "RestId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    CREATE INDEX "IX_Products_RestId" ON "Products" ("RestId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Restaurants_RestId" FOREIGN KEY ("RestId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201105183408_ProductsUpdate', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Restaurants_RestId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" RENAME COLUMN "RestId" TO "RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER INDEX "IX_Products_RestId" RENAME TO "IX_Products_RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201105192026_ProductsUpdate2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

