CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201027003800_InitialMigration') THEN
    CREATE TABLE "Restaurants" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ImgPath" text NULL,
        CONSTRAINT "PK_Restaurants" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201027003800_InitialMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201027003800_InitialMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201030213552_InitialMigration2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201030213552_InitialMigration2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101001222_MigrationProducts') THEN
    CREATE TABLE "Products" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "ImgPath" text NULL,
        "Description" text NULL,
        "Price" real NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101001222_MigrationProducts') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101001222_MigrationProducts', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101164712_UsersMigration') THEN
    CREATE TABLE "Users" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NULL,
        "Email" text NULL,
        "PasswordHash" bytea NULL,
        "PasswordSalt" bytea NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101164712_UsersMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101164712_UsersMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101183159_MigrationProductsOfRestaurant') THEN
    ALTER TABLE "Products" ADD "IdRest" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201101183159_MigrationProductsOfRestaurant') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201101183159_MigrationProductsOfRestaurant', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201103094826_Deploy') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201103094826_Deploy', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    ALTER TABLE "Products" RENAME COLUMN "IdRest" TO "RestId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    CREATE INDEX "IX_Products_RestId" ON "Products" ("RestId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Restaurants_RestId" FOREIGN KEY ("RestId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105183408_ProductsUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201105183408_ProductsUpdate', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Restaurants_RestId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" RENAME COLUMN "RestId" TO "RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER INDEX "IX_Products_RestId" RENAME TO "IX_Products_RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201105192026_ProductsUpdate2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201105192026_ProductsUpdate2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    ALTER TABLE "Products" ADD "OrderId" integer NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    CREATE TABLE "Orders" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "BuyDateTime" timestamp without time zone NOT NULL,
        "UserId" integer NULL,
        "RestaurantId" integer NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Orders_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    CREATE INDEX "IX_Products_OrderId" ON "Products" ("OrderId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    CREATE INDEX "IX_Orders_RestaurantId" ON "Orders" ("RestaurantId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    CREATE INDEX "IX_Orders_UserId" ON "Orders" ("UserId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    ALTER TABLE "Products" ADD CONSTRAINT "FK_Products_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106001913_OrdersMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201106001913_OrdersMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    ALTER TABLE "Products" DROP CONSTRAINT "FK_Products_Orders_OrderId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    DROP INDEX "IX_Products_OrderId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    ALTER TABLE "Products" DROP COLUMN "OrderId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    CREATE TABLE "OrderProduct" (
        "OrdersId" integer NOT NULL,
        "ProductsId" integer NOT NULL,
        CONSTRAINT "PK_OrderProduct" PRIMARY KEY ("OrdersId", "ProductsId"),
        CONSTRAINT "FK_OrderProduct_Orders_OrdersId" FOREIGN KEY ("OrdersId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrderProduct_Products_ProductsId" FOREIGN KEY ("ProductsId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    CREATE INDEX "IX_OrderProduct_ProductsId" ON "OrderProduct" ("ProductsId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106004411_OrdersMigration2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201106004411_OrdersMigration2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106102914_OrdersProductsMigration1') THEN
    DROP TABLE "OrderProduct";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106102914_OrdersProductsMigration1') THEN
    CREATE TABLE "OrdersProducts" (
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "Quantity" integer NOT NULL,
        CONSTRAINT "PK_OrdersProducts" PRIMARY KEY ("OrderId", "ProductId"),
        CONSTRAINT "FK_OrdersProducts_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_OrdersProducts_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106102914_OrdersProductsMigration1') THEN
    CREATE INDEX "IX_OrdersProducts_ProductId" ON "OrdersProducts" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106102914_OrdersProductsMigration1') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201106102914_OrdersProductsMigration1', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106125508_OrdersProductsMigration2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201106125508_OrdersProductsMigration2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106183230_ProductCategories') THEN
    ALTER TABLE "Products" ADD "Category" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201106183230_ProductCategories') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201106183230_ProductCategories', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Restaurants_RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Users_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" ALTER COLUMN "UserId" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "UserId" SET DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" ALTER COLUMN "RestaurantId" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "RestaurantId" SET DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201108002934_NewOrderProductsMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201108002934_NewOrderProductsMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Restaurants_RestaurantId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Users_UserId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" ALTER COLUMN "UserId" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "UserId" SET DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" ALTER COLUMN "RestaurantId" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "RestaurantId" SET DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES "Restaurants" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112140842_RebaseMigration') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201112140842_RebaseMigration', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201112141446_RebaseMigration2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201112141446_RebaseMigration2', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201118150935_AuthSalt') THEN
    ALTER TABLE "Users" ADD "AuthSalt" bytea NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20201118150935_AuthSalt') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20201118150935_AuthSalt', '5.0.0-rc.2.20475.6');
    END IF;
END $$;
COMMIT;

