CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Restaurants" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ImgPath" text NULL,
    CONSTRAINT "PK_Restaurants" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201027003800_InitialMigration', '5.0.0-rc.2.20475.6');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201030213552_InitialMigration2', '5.0.0-rc.2.20475.6');

COMMIT;

START TRANSACTION;

CREATE TABLE "Products" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "ImgPath" text NULL,
    "Description" text NULL,
    "Price" real NOT NULL,
    CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201101001222_MigrationProducts', '5.0.0-rc.2.20475.6');

COMMIT;

START TRANSACTION;

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NULL,
    "Email" text NULL,
    "PasswordHash" bytea NULL,
    "PasswordSalt" bytea NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201101164712_UsersMigration', '5.0.0-rc.2.20475.6');

COMMIT;

START TRANSACTION;

ALTER TABLE "Products" ADD "IdRest" integer NOT NULL DEFAULT 0;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201101183159_MigrationProductsOfRestaurant', '5.0.0-rc.2.20475.6');

COMMIT;

